### PR TITLE
Make graphite2 python module exportable

### PR DESCRIPTION
**Pull request by bgermann**
Use graphite2 instead of graphite as module name because there is
already a graphite package on PyPI. Add a setup.py with metadata to
enable creation of wheel packages.

### CODE REVIEW

**Comment by bgermann** [comment]
After merging this PR it should be published on PyPI. dockcross is a good starting point to look into compiling binary wheels for the common operating systems.

**Comment by bgermann** [comment]
graphite2.py does not have a MPL license statement on its file. With MPL being a file based license (as opposed to project-wide, like LGPL), one could interpret it as being LGPL-licensed only. It would make sense to add MPL to the license header as in all other files.

Also, adding the MPL license text in a LICENSE.MPL file would clarify the license being applicable.

**Comment by tim-eves** [comment]
Thanks for all the work, this looks good, though there are a couple of questions:
1. I'm concerned that the name graphite2 is too close to the pre-exisiting graphite pypi package, I've notice that the snappy compression library has adopted python-snappy I wonder if python-graphite2 would be more meaning ful since the is a ctypes wrapper over a C++ lib. Or perhaps call the package libgraphite2 but that seems to have less evidence as a convention in pypi.
2. Judging by the dockcross mention, wheel etc am I correct in thinking the idea is you'll treat test/graphite.py as an artifact of the graphite project.  Currently it's solely for testing and is not installed or considered a publishable artifact, but we're very open to having it as a deliverable, in which case I'll move from test into a separate top-level dir and update the documentation accordingly.

Some of the updates to graphite.py are overlapping with current work in upgrading the graphite projects scripts to python3, I'm happy enough to apply as is but it would then be promptly updated and I'd like those updates to go into the eventual pypyi package. I will ensure that the module remains python2.7 & 3.6+ compatible even if the in repo users are all going to 3.

**Comment by bgermann** [comment]
1. I do not think you should change the PyPI distribution name. The not-yet-final PEP 423 suggests using the module name and explicitly mentions python- prefixes as bad style. If you want to use libgraphite2, you should also change the module name. I would still prefer graphite2.

2. Yes, treating it as a deliverable is my idea. It is already used downstream by graide, which is why I submitted this PR. The .py file is actually moved to the top directory in this PR already.

Thank you for taking on this work. I'm fine with however you decide to update it next.

**Comment by tim-eves** [comment]
Okay let's keep it called graphite2, it seems the least bad option :-)

**Comment by tim-eves** [comment]
Merged in commit 08f2aca62f60e52d27a7d06d6459ea24398c03fa

**Comment by tim-eves** [comment]
I've added a fix in commit 1ac4f70b5ab951e75d1cbbb59319ad202a32b4e9 this will need to be included in your graphit2 pypi package.  I am assuming you going to upload that to Pypi, is that assumption correct

**Comment by bgermann** [comment]
If you are okay with that, I will do it, but for the next version. By the way, there is a version string in setup.py which has to be updated (is at 1.3.11).

**Pull request closed without merging**
